package com.example.taskflow.migration;

import db.migration.V21__fix_double_booking_index;
import org.flywaydb.core.api.migration.Context;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class FlywayMigrationTest {

    @Test
    void v21KeepsOneActiveSlotAndAllowsRepeatedDeniedRowsOnH2() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:v21-migration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1")) {
            connection.createStatement().execute("""
                    CREATE TABLE appointments (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        barber_name VARCHAR(100) NOT NULL,
                        booking_date DATE NOT NULL,
                        booking_time VARCHAR(50) NOT NULL,
                        status VARCHAR(50) NOT NULL,
                        updated_at TIMESTAMP NOT NULL
                    )
                    """);
            connection.createStatement().executeUpdate("""
                    INSERT INTO appointments (barber_name, booking_date, booking_time, status, updated_at)
                    VALUES ('Alex', DATE '2030-01-02', '9:00', 'PENDING', CURRENT_TIMESTAMP),
                           ('Alex', DATE '2030-01-02', '09:00', 'PENDING', CURRENT_TIMESTAMP)
                    """);

            Context context = Mockito.mock(Context.class);
            Mockito.when(context.getConnection()).thenReturn(connection);
            new V21__fix_double_booking_index().migrate(context);

            assertEquals(1, count(connection, "PENDING"));
            assertEquals(1, count(connection, "DENIED"));

            connection.createStatement().executeUpdate("""
                    INSERT INTO appointments (barber_name, booking_date, booking_time, status, updated_at)
                    VALUES ('Alex', DATE '2030-01-02', '09:00', 'DENIED', CURRENT_TIMESTAMP)
                    """);

            assertThrows(SQLException.class, () -> connection.createStatement().executeUpdate("""
                    INSERT INTO appointments (barber_name, booking_date, booking_time, status, updated_at)
                    VALUES ('Alex', DATE '2030-01-02', '09:00', 'APPROVED', CURRENT_TIMESTAMP)
                    """));
        }
    }

    private static int count(Connection connection, String status) throws SQLException {
        try (var statement = connection.prepareStatement(
                "SELECT COUNT(*) FROM appointments WHERE status = ?")) {
            statement.setString(1, status);
            try (var result = statement.executeQuery()) {
            result.next();
            return result.getInt(1);
            }
        }
    }
}
