name: Angular Browser Test

on:
  workflow_dispatch:

jobs:
  browser-test:
    runs-on: ubuntu-latest

    container:
      image: grafana/k6:master-with-browser

    env:
      BASE_URL: ${{ vars.BASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Run browser test
        run: |
          k6 run k6/browser.js
